name: Build thread
on:
  repository_dispatch:
  workflow_dispatch:
jobs: 
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        D1: [0,1,2]
        D2: [0,2]
      fail-fast: false
    steps:
    - name: Run checkout@v2.3.4
      uses: actions/checkout@v2.3.4
